Northwind.Web/Areas/Report/Controllers/AdminCustomersController.cs
using Northwind.WebApi.DTO;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace Northwind.Web.Areas.Report.Controllers
{
    [ClaimsAuthorize(ClaimTypes.Role, "Admin", "Manager")]
    public class AdminCustomersController : Controller
    {
        private readonly ICustomerSearchService _customerSearchService;

        public AdminCustomersController(ICustomerSearchService customerSearchService)
        {
            _customerSearchService = customerSearchService;
        }

        public ActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public async Task<ViewResult> OneOrZeroOrders()
        {
            ViewBag.Message = "Only for editors!";

            IEnumerable<string> customersNames = await _customerSearchService.GetCustomersNamesAsync(new SearchOrderCriteriaDTO { LessOrEqualOrders = 1 });
            return View(customersNames);
        }
    }
}

Northwind.Web/Areas/Report/Controllers/CustomersController.cs
using Newtonsoft.Json;
using Northwind.WebApi.DTO;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace Northwind.Web.Areas.Report.Controllers
{
    //[ClaimsAuthorize(ClaimTypes.Role,"Admin", "Manager")]
    public class CustomersController : Controller
    {
        private readonly ICustomerSearchService _customerSearchService;

        public CustomersController(ICustomerSearchService customerSearchService)
        {
            _customerSearchService = customerSearchService;
        }

        public ActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public async Task<ViewResult> OneOrZeroOrders()
        {
            IEnumerable<string> customersNames = await _customerSearchService.GetCustomersNamesAsync(new SearchOrderCriteriaDTO { LessOrEqualOrders = 1 });
            return View(customersNames);
        }

        [HttpGet]
        public ViewResult OneOrZeroOrdersWithAngular()
        {
            ViewBag.RootUrl = GetRootUrl();
            return View();
        }

        [HttpGet]
        public async Task<ViewResult> OneOrZeroOrdersWithReact()
        {
            IEnumerable<string> customersNames = await _customerSearchService.GetCustomersNamesAsync(new SearchOrderCriteriaDTO { LessOrEqualOrders = 1 });

            ViewBag.Customers = JsonConvert.SerializeObject(customersNames.Select((s, i) => new { customer = s }));
            ViewBag.RootUrl = GetRootUrl();

            return View();
        }

        private string GetRootUrl()
        {
            var appPath = string.Empty;
            var context = HttpContext;
            if (context != null)
            {
                appPath = string.Format("{0}://{1}{2}{3}",
                                        context.Request.Url.Scheme,
                                        context.Request.Url.Host,
                                        context.Request.Url.Port == 80
                                            ? string.Empty
                                            : ":" + context.Request.Url.Port,
                                        context.Request.ApplicationPath);
            }

            if (!appPath.EndsWith("/"))
                appPath += "/";

            return appPath;
        }

        [HttpGet]
        public async Task<JsonResult> GetCustomersNames(int lrange, int rrange)
        {
            IEnumerable<string> customersNames = await _customerSearchService.GetCustomersNamesAsync(new SearchOrderCriteriaDTO { LessOrEqualOrders = 1 });
            return Json(new { Data = customersNames.Select(s => new { name = s}) }, JsonRequestBehavior.AllowGet);
        }
    }
}

Northwind.Web/Areas/Report/Controllers/SecuredCustomersController.cs
using Northwind.WebApi.DTO;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace Northwind.Web.Areas.Report.Controllers
{
    [Authorize]
    public class SecuredCustomersController : Controller
    {
        private readonly ICustomerSearchService _customerSearchService;

        public SecuredCustomersController(ICustomerSearchService customerSearchService)
        {
            _customerSearchService = customerSearchService;
        }

        public ActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public async Task<ViewResult> OneOrZeroOrders()
        {
            ViewBag.Message = "Only for authenticated users!";

            IEnumerable<string> customersNames = await _customerSearchService.GetCustomersNamesAsync(new SearchOrderCriteriaDTO { LessOrEqualOrders = 1 });
            return View("OneOrZeroOrders", customersNames);
        }
    }
}

Northwind.Web/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Web;
using System.Web.Mvc;

namespace Northwind.Web.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

Northwind.Web/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

Northwind.Web/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

Northwind.Web/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>Reporting</h1>
    <p class="lead">Please select an action</p>
    <div class="dropdown">
        <button class="btn btn-default dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
            Report for customers with one or zero orders
            <span class="caret"></span>
        </button>
        <ul class="dropdown-menu" aria-labelledby="dropdownMenu1">
            <li>@Html.ActionLink("Datatables", "OneOrZeroOrders", "Customers", new { Area = "Report" }, new { @class = "" })</li>
            <li>@Html.ActionLink("Angular", "OneOrZeroOrdersWithAngular", "Customers", new { Area = "Report" }, new { @class = "" })</li>
            <li>@Html.ActionLink("React", "OneOrZeroOrdersWithReact", "Customers", new { Area = "Report" }, new { @class = "" })</li>
            <li>@Html.ActionLink("Datatables for authenticated users", "OneOrZeroOrders", "SecuredCustomers", new { Area = "Report" }, new { @class = "" })</li>
            <li>@Html.ActionLink("Datatables with edit rights", "OneOrZeroOrders", "AdminCustomers", new { Area = "Report" }, new { @class = "" })</li>
        </ul>
    </div>


</div>